[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --chip esp32s3 --after watchdog-reset"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
